/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seminarski.forms;
import javax.swing.JOptionPane;
import seminarski.controller.Controller;
import seminarski.domain.*;
import java.util.ArrayList;
/**
 *
 * @author pc
 */
public class NivoTakmicenjaForm extends javax.swing.JDialog {

    /**
     * Creates new form NivoTakmicenjaForm
     */
    public NivoTakmicenjaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos nivoa takmicenja");
        popuniCombo();
        forInsert();
    }
    
    public NivoTakmicenjaForm(java.awt.Frame parent, boolean modal,NivoTakmicenja nt) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Detaljan prikaz nivoa takmicenja");
        popuniCombo();
        forView(nt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboNivo = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId.setText("id");

        jLabel1.setText("nivo takmicenja");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(comboNivo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        NivoTakmicenja nivo=new NivoTakmicenja();
        if(ponovanUnos()==false){
            nivo.setNaziv((String)comboNivo.getSelectedItem());
            int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate nivo?","Potvrda",JOptionPane.YES_NO_OPTION);
            if(odg==0){
                nivo.setId(Controller.getInstance().kreirajNivo(nivo));
                if(nivo.getId()!=0){
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Greska prilikom cuvanja nivoa","Greska",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nece biti sacuvano!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nivo vec postoji u bazi","Obavestenje",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        NivoTakmicenja stari_nivo=new NivoTakmicenja();
        stari_nivo.setId(Long.parseLong(txtId.getText()));
        stari_nivo.setNaziv((String)comboNivo.getSelectedItem());
        int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete nivo takmiceja?","Potvrda",JOptionPane.YES_NO_OPTION);
        if(odg==0){
            
            ArrayList<Takmicenje> takmicenje_brisanje=Controller.getInstance().vratiListuTakmicenja(stari_nivo);
            ArrayList<StavkaTakmicenja> stvake_brisanje=new ArrayList<StavkaTakmicenja>();
            for(Takmicenje t:takmicenje_brisanje){
                ArrayList<StavkaTakmicenja> li=Controller.getInstance().vratiListuStavkiTakmicenja(t);
                for(StavkaTakmicenja sss:li){
                    stvake_brisanje.add(sss);
                }
            }
            for(StavkaTakmicenja st:stvake_brisanje){
                if(Controller.getInstance().obrisiStavkuStavke(st)){
                }
            }
            for(Takmicenje t:takmicenje_brisanje){
                if(Controller.getInstance().obrisiStavkuTakmicenja(t)){
                }
            }
            if(Controller.getInstance().obrisiTakmicenje(stari_nivo)){
                if(Controller.getInstance().obrisiNivoTakmicenja(stari_nivo)){
                    JOptionPane.showMessageDialog(this, "Uspesno obrisano");
                    this.setVisible(false);
                    new PrikazNivoTakmicenjaForm(null, true).setVisible(true);
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Nece biti obrisnao");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivoTakmicenjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivoTakmicenjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivoTakmicenjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivoTakmicenjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NivoTakmicenjaForm dialog = new NivoTakmicenjaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void popuniCombo(){
        String[] nivoi={"Skolsko takmicenje","Opstinsko takmicenje","Okruzno takmicenje","Republicko takmicenje"};
        for(String s:nivoi){
            comboNivo.addItem(s);
        }
        comboNivo.setSelectedItem(null);
    }
    
    private void forInsert(){
        txtId.setVisible(false);
        lblId.setVisible(false);
        btnObrisi.setVisible(false);
    }
    
    private boolean ponovanUnos(){
        ArrayList<NivoTakmicenja> svi=Controller.getInstance().vratiListuSviNivoiTakmicenja();
        NivoTakmicenja nivo=new NivoTakmicenja();
        nivo.setNaziv((String)comboNivo.getSelectedItem());
        for(NivoTakmicenja n:svi){
            if(n.getNaziv().equals(nivo.getNaziv())){
                return true;
            }
        }
        return false;
    }
    
    private void forView(NivoTakmicenja nt){
        btnSacuvaj.setVisible(false);
        jLabel2.setVisible(false);
        txtId.setText(nt.getId()+"");
        comboNivo.setSelectedItem(nt.getNaziv());
        txtId.setEnabled(false);
        comboNivo.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> comboNivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
