/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seminarski.forms;
import javax.swing.JOptionPane;
import seminarski.controller.Controller;
import seminarski.domain.*;
import java.util.ArrayList;
/**
 *
 * @author pc
 */
public class PredmetForm extends javax.swing.JDialog {

    /**
     * Creates new form PredmetForm
     */
    public PredmetForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos predmeta");
        forInsert();
    }
    
    public PredmetForm(java.awt.Frame parent, boolean modal,Predmet predmet) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Detaljan prikaz predmeta");
        forView(predmet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId.setText("id");

        jLabel1.setText("naziv");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPromeni.setText("Omoguci promenu");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacuvaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPromeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPromeni))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Predmet predmet=new Predmet();
        if(novUnos()==false){
            predmet.setNaziv(txtNaziv.getText().trim());
            int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate novi predmet?","Potvrdite",JOptionPane.YES_NO_OPTION);
            if(odg==0){
                predmet.setId(Controller.getInstance().kreirajPredmet(predmet));
                if(predmet.getId()!=0){
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Greska prilikom cuvanja predmeta","Greska",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nece biti sacuvano!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Predmet vec postoji u bazi","Obavestenje",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        Predmet stariPredmet=new Predmet();
        stariPredmet.setId(Long.parseLong(txtId.getText()));
        stariPredmet.setNaziv(txtNaziv.getText());
        int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete predmet?","Provera",JOptionPane.YES_NO_OPTION);
        if(odg==0){
            ArrayList<Takmicenje> takmicenje_brisanje=Controller.getInstance().vratiListuTakmicenja(stariPredmet);
            ArrayList<StavkaTakmicenja> stvake_brisanje=new ArrayList<StavkaTakmicenja>();
            for(Takmicenje t:takmicenje_brisanje){
                ArrayList<StavkaTakmicenja> li=Controller.getInstance().vratiListuStavkiTakmicenja(t);
                for(StavkaTakmicenja sss:li){
                    stvake_brisanje.add(sss);
                }
            }
            
            for(Takmicenje tt:takmicenje_brisanje){
                if(Controller.getInstance().obrisiSala(tt)){
                }
            }
            
            for(StavkaTakmicenja st:stvake_brisanje){
                if(Controller.getInstance().obrisiStavkuStavke(st)){
                }
            }
            for(Takmicenje t:takmicenje_brisanje){
                if(Controller.getInstance().obrisiStavkuTakmicenja(t)){
                }
            }
            
            if(Controller.getInstance().obrisiTakmicenje(stariPredmet)){
                if(Controller.getInstance().obrisiPredmet(stariPredmet)){
                    JOptionPane.showMessageDialog(this, "Uspesno obrisano");
                    this.setVisible(false);
                    new PrikazPredmetaForm(null, true).setVisible(true);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nece biti obrisano");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        btnSacuvaj.setVisible(false);
        btnIzmeni.setVisible(true);
        btnPromeni.setVisible(false);
        txtNaziv.setEnabled(true);
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Predmet zaIzmenu=new Predmet();
        zaIzmenu.setId(Long.parseLong(txtId.getText()));
        zaIzmenu.setNaziv(txtNaziv.getText());
        int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate izmene?","Potvrda",JOptionPane.YES_NO_OPTION);
        if(odg==0){
            if(Controller.getInstance().promeniPredmet(zaIzmenu)){
                JOptionPane.showMessageDialog(this, "Uspesno sacuvane izmene");
                this.setVisible(false);
                new PrikazPredmetaForm(null, true).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Greska prilikom cuvanja izmena.","Greska",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nece biti izmenjeno");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PredmetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PredmetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PredmetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PredmetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PredmetForm dialog = new PredmetForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void forInsert(){
        txtId.setVisible(false);
        lblId.setVisible(false);
        btnObrisi.setVisible(false);
        btnIzmeni.setVisible(false);
        btnPromeni.setVisible(false);
    }
    
    private void forView(Predmet p){
        btnSacuvaj.setVisible(false);
        jLabel2.setVisible(false);
        txtId.setText(p.getId()+"");
        txtNaziv.setText(p.getNaziv());
        txtId.setEnabled(false);
        txtNaziv.setEnabled(false);
        btnIzmeni.setVisible(false);
    }
    
    private boolean novUnos(){
        ArrayList<Predmet> svi=Controller.getInstance().vratiListuSviPredmet();
        Predmet p=new Predmet();
        p.setNaziv(txtNaziv.getText().trim());
        for(Predmet predmet:svi){
            if(predmet.getNaziv().equals(p.getNaziv())){
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
