/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seminarski.forms;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import seminarski.controller.Controller;
import seminarski.domain.*;
/**
 *
 * @author pc
 */
public class SalaForm extends javax.swing.JDialog {

    /**
     * Creates new form ProbaSalaForm
     */
    public SalaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(800, 500);
        setTitle("Unos dezurstvo");
        forInsert();
        popuniComboNastavnik();
        popuniComboTakmicenje();
        comboTakmicenje.addActionListener(event->{
            comboStavka.removeAllItems();
            ArrayList<StavkaTakmicenja> list=Controller.getInstance().vratiListuStavkiTakmicenja((Takmicenje)comboTakmicenje.getSelectedItem());
            for(StavkaTakmicenja st:list){
                comboStavka.addItem(st);
            }
            comboStavka.setSelectedItem(null);
        });
    }
    
    
    
    public SalaForm(java.awt.Frame parent, boolean modal, Sala sala) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pregled dezurstva");
        popuniComboNastavnik();
        popuniComboTakmicenje();
        comboTakmicenje.addActionListener(event->{
            comboStavka.removeAllItems();
            ArrayList<StavkaTakmicenja> list=Controller.getInstance().vratiListuStavkiTakmicenja((Takmicenje)comboTakmicenje.getSelectedItem());
            for(StavkaTakmicenja st:list){
                comboStavka.addItem(st);
            }
        });
        forView(sala);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboNastavnik = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTakmicenje = new javax.swing.JComboBox<>();
        comboStavka = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtBrojSale = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVremeDezurstva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtH = new javax.swing.JTextField();
        txtMIN = new javax.swing.JTextField();
        spinerSati = new javax.swing.JSpinner();
        spinerMinuti = new javax.swing.JSpinner();
        btnSacuvaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setText("natavnik koji se prijavljuje za dezurstvo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboNastavnik, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNastavnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Unos dezurstva");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setText("takmicenje na koje se odnosi dezurstvo:");

        jLabel4.setText("takmicenje za razred:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTakmicenje, 0, 434, Short.MAX_VALUE)
                    .addComponent(comboStavka, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTakmicenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboStavka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel5.setText("broj sale u kojoj se takmicenje odrzava:");

        jLabel6.setText("vreme pocetka dezurstva:");

        jLabel7.setText("trajanje dezurstva:");

        txtH.setText("h");

        txtMIN.setText("min");

        spinerSati.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        spinerMinuti.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(spinerSati, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(spinerMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBrojSale)
                        .addComponent(txtVremeDezurstva, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVremeDezurstva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinerSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinerMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(644, 644, 644))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPromeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnObrisi))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPromeni))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        Sala sala=new Sala();
        if(daLiJeSveUneto()){
            sala.setNastavnik((Nastavnik)comboNastavnik.getSelectedItem());
            sala.setTakmicenje((Takmicenje)comboTakmicenje.getSelectedItem());
            sala.setStavka((StavkaTakmicenja)comboStavka.getSelectedItem());
            sala.setBroj_sale(Integer.parseInt(txtBrojSale.getText()));
            sala.setVreme_pocetka(txtVremeDezurstva.getText());
            sala.setTrajanje(spinerSati.getValue()+txtH.getText()+" "+spinerMinuti.getValue()+txtMIN.getText());
            int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate?","Potvrda",JOptionPane.YES_NO_OPTION);
            if(odg==0){
                if(Controller.getInstance().UbaciSalaAsocijativna(sala)){
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvano");
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Greska prilikom cuvanja u bazi","Greska",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nece biti sacuvano");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Potrebno je uneti sva obavezna polja","Greska",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        Sala zaBrisanje=new Sala();
        zaBrisanje.setNastavnik((Nastavnik)comboNastavnik.getSelectedItem());
        zaBrisanje.setTakmicenje((Takmicenje)comboTakmicenje.getSelectedItem());
        zaBrisanje.setStavka((StavkaTakmicenja)comboStavka.getSelectedItem());
        zaBrisanje.setBroj_sale(Integer.parseInt(txtBrojSale.getText()));
        zaBrisanje.setVreme_pocetka(txtVremeDezurstva.getText());
        zaBrisanje.setTrajanje(spinerSati.getValue()+txtH.getText()+" "+spinerMinuti.getValue()+txtMIN.getText());
        int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete?","Potvrda",JOptionPane.YES_NO_OPTION);
        if(odg==0){
            if(Controller.getInstance().obrisiSalu(zaBrisanje)){
                JOptionPane.showMessageDialog(this, "Uspesno obrisano");
                this.setVisible(false);
                new PrikazSaleForm(null, true).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Greska prilikom brisanja iz baze","Greska",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nece biti obrisano!");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        btnIzmeni.setVisible(true);
        btnPromeni.setVisible(false);
        txtBrojSale.setEnabled(true);
        txtVremeDezurstva.setEnabled(true);
        spinerMinuti.setEnabled(true);
        spinerSati.setEnabled(true);
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Sala zaIzmenu=new Sala();
        zaIzmenu.setNastavnik((Nastavnik)comboNastavnik.getSelectedItem());
        zaIzmenu.setTakmicenje((Takmicenje)comboTakmicenje.getSelectedItem());
        zaIzmenu.setStavka((StavkaTakmicenja)comboStavka.getSelectedItem());
        zaIzmenu.setBroj_sale(Integer.parseInt(txtBrojSale.getText()));
        zaIzmenu.setVreme_pocetka(txtVremeDezurstva.getText());
        zaIzmenu.setTrajanje(spinerSati.getValue()+txtH.getText()+" "+spinerMinuti.getValue()+txtMIN.getText());
        int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate izmene?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if(odg==0){
            if(Controller.getInstance().promeniSala(zaIzmenu)){
                JOptionPane.showMessageDialog(this, "Uspesno izmenjeno");
                this.setVisible(false);
                new PrikazSaleForm(null, true).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Greska prilikom cuvanja izmena","Greska",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nece biti sacuvane izmene!");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalaForm dialog = new SalaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void forInsert(){
        btnObrisi.setVisible(false);
        btnPromeni.setVisible(false);
        btnIzmeni.setVisible(false);
    }
    
    private void forView(Sala sala){
        btnSacuvaj.setVisible(false);
        txtBrojSale.setText(sala.getBroj_sale()+"");
        txtVremeDezurstva.setText(sala.getVreme_pocetka());
        comboNastavnik.setSelectedItem(sala.getNastavnik());
        comboTakmicenje.setSelectedItem(sala.getTakmicenje());
        comboStavka.setSelectedItem(sala.getStavka());
        String[] nizTrajanje=sala.getTrajanje().split(" ");
        char[] sati=nizTrajanje[0].toCharArray();
        int sat=Character.getNumericValue(sati[0]);
        spinerSati.setValue(sat);
        char[] minuti=nizTrajanje[1].toCharArray();
        String s = "";
        for(char c : minuti) {
            if(Character.isDigit(c))
                s+=c;
        }
        if(s.equals("0")) 
            spinerMinuti.setValue(0);
        else 
            spinerMinuti.setValue(Integer.parseInt(s));
        
        comboNastavnik.setEnabled(false);
        comboStavka.setEnabled(false);
        comboTakmicenje.setEnabled(false);
        txtBrojSale.setEnabled(false);
        txtH.setEnabled(false);
        txtMIN.setEnabled(false);
        txtVremeDezurstva.setEnabled(false);
        spinerMinuti.setEnabled(false);
        spinerSati.setEnabled(false);
        btnIzmeni.setVisible(false);
        
    }
    
    
    private void popuniComboNastavnik(){
        ArrayList<Nastavnik> list=Controller.getInstance().vratiListuSviNastavnik();
        for(Nastavnik n:list){
            comboNastavnik.addItem(n);
        }
        comboNastavnik.setSelectedItem(null);
    }
    
    private void popuniComboTakmicenje(){
        ArrayList<Takmicenje> lista=Controller.getInstance().vratiListuSviTakmicenja();
        for(Takmicenje t:lista){
            comboTakmicenje.addItem(t);
        }
        comboTakmicenje.setSelectedItem(null);
    }
    
    private boolean daLiJeSveUneto(){
        if(comboNastavnik.getSelectedItem().equals(null) || comboTakmicenje.getSelectedItem().equals(null) || comboStavka.getSelectedItem().equals(null) || txtBrojSale.getText().equals("") || txtVremeDezurstva.getText().equals("") || spinerSati.getValue().equals(0)){
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Nastavnik> comboNastavnik;
    private javax.swing.JComboBox<StavkaTakmicenja> comboStavka;
    private javax.swing.JComboBox<Takmicenje> comboTakmicenje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner spinerMinuti;
    private javax.swing.JSpinner spinerSati;
    private javax.swing.JTextField txtBrojSale;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtMIN;
    private javax.swing.JTextField txtVremeDezurstva;
    // End of variables declaration//GEN-END:variables
}
