/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seminarski.forms;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import seminarski.controller.Controller;
import seminarski.domain.*;
/**
 *
 * @author pc
 */
public class UnosRezultataForm extends javax.swing.JDialog {

    /**
     * Creates new form UnosRezultataForm
     */
    public UnosRezultataForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    public UnosRezultataForm(java.awt.Frame parent, boolean modal, StavkaStavkeTakmicenja sst, StavkaTakmicenja st, Ucenik u) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Unos rezultata takmicenja");
        txtNazivTakmicenja.setText(st.toString());
        txtImeUcenika.setText(u.toString());
        txtNazivTakmicenja.setEnabled(false);
        txtImeUcenika.setEnabled(false);
        radioPrvoMesto.setEnabled(false);
        radioDrugoMesto.setEnabled(false);
        radioTreceMesto.setEnabled(false);
        StavkaStavkeTakmicenja stavka_za_izmenu=sst;
        txtBrojPoena.addActionListener(e->{
            ButtonGroup grupa=new ButtonGroup();
            grupa.add(radioPrvoMesto);
            grupa.add(radioDrugoMesto);
            grupa.add(radioTreceMesto);
            grupa.clearSelection();
            stavka_za_izmenu.setBr_poena(Integer.parseInt(txtBrojPoena.getText()));
            
            if(stavka_za_izmenu.getBr_poena()<=100 && stavka_za_izmenu.getBr_poena()>85){
                stavka_za_izmenu.setRang(Rang.PRVO_MESTO);
                radioPrvoMesto.setSelected(true);
            }else if(stavka_za_izmenu.getBr_poena()<=85 && stavka_za_izmenu.getBr_poena()>65){
                stavka_za_izmenu.setRang(Rang.DRUGO_MESTO);
                radioDrugoMesto.setSelected(true);
            }else if(stavka_za_izmenu.getBr_poena()<=65 && stavka_za_izmenu.getBr_poena()>51){
                stavka_za_izmenu.setRang(Rang.TRECE_MESTO);
                radioTreceMesto.setSelected(true);
            }else{
                stavka_za_izmenu.setRang(Rang.BEZ_RANGA);
            }
            
        });
        
        
        btnPotvrdai.addActionListener(event->{
            int odg=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate?","Potvrda",JOptionPane.YES_NO_OPTION);
            if(odg==0){
                if(Controller.getInstance().promenaStavkeStavkeTakmicenja(sst)){
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvane izmene!");
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Greska pri cuvanju u bazi","Greska",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Nece biti obrisano!");
            }
        
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivTakmicenja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImeUcenika = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBrojPoena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioPrvoMesto = new javax.swing.JRadioButton();
        radioDrugoMesto = new javax.swing.JRadioButton();
        radioTreceMesto = new javax.swing.JRadioButton();
        btnPotvrdai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("naziv takmicenja");

        jLabel2.setText("ime ucenika");

        jLabel3.setText("ostvaren broj poena");

        jLabel4.setText("ostvaren rang");

        radioPrvoMesto.setText("prvo mesto");

        radioDrugoMesto.setText("drugo mesto");

        radioTreceMesto.setText("trece mesto");

        btnPotvrdai.setText("Potvrdi");
        btnPotvrdai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioTreceMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioDrugoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrojPoena, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPrvoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNazivTakmicenja)
                        .addComponent(txtImeUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPotvrdai)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivTakmicenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImeUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojPoena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioPrvoMesto))
                .addGap(18, 18, 18)
                .addComponent(radioDrugoMesto)
                .addGap(18, 18, 18)
                .addComponent(radioTreceMesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPotvrdai)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPotvrdaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPotvrdaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosRezultataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosRezultataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosRezultataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosRezultataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnosRezultataForm dialog = new UnosRezultataForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotvrdai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton radioDrugoMesto;
    private javax.swing.JRadioButton radioPrvoMesto;
    private javax.swing.JRadioButton radioTreceMesto;
    private javax.swing.JTextField txtBrojPoena;
    private javax.swing.JTextField txtImeUcenika;
    private javax.swing.JTextField txtNazivTakmicenja;
    // End of variables declaration//GEN-END:variables
}
